### ISSUE TITLE
Display comments as tree.

### ISSUE THREAD

**Issue by JonnyCodewalker** [mdh34/hackup#13]
Currently in order to read the comments on an article one has to click on the replies button for every non top level comment. That makes browsing/reading the comments rather tedious. I would suggest having at least the option to display comments after the top level comment (when clicking on the replies button) in a reddit-like fashion to maintain the clean look of the comment section at the beginnign without sacrificing to much usability.

**Comment by eljefuri** [comment]
Agreed with @JonnyCodewalker being able to view the comments as a tree would make this app far more useful. Thanks for your consideration Matt.

**Comment by ranfdev** [comment]
![screenshot from 2019-03-06 00 21 57](https://user-images.githubusercontent.com/23294184/53844425-ec697a00-3fa5-11e9-8ad6-3f9f4bfb4e67.png)
I made this. It's a similar experience to the original website. If you want to collapse a comment, just uncheck "replies". Is this ok?

**Comment by mdh34** [comment]
Fixed by #29
