### ISSUE TITLE
"Score" and "Comments" font color makes text really hard to read

### ISSUE THREAD

**Issue by eljefuri** [mdh34/hackup#23]
Maybe it calls me out as an old man, but I find the font color chosen for the "Score" and "Comments" indicators on the left bar really hard on my eyes. This is true in both light and dark modes, but especially in dark mode. Perhaps a different color scheme can be found? Thanks Matt.

**Comment by mdh34** [comment]
I can appreciate the contrast issues with the orange text - out of interest are you using the default elementary theme?

I might add a high-contrast theme option if that's something that would be useful

**Comment by eljefuri** [comment]
Hi @mdh34 Yes, I am using the default Elementary theme. This isn't a big deal really and I don't know if I am blind enough to need a high-contrast theme! Some minor adjustments to the default styling would be nice though!

**Comment by mdh34** [comment]
The orange currently used is the same as that on the hn website, so I might tweak that or alternative the 'high-contrast' option is really just a subtle colour change, something like this:
![image](https://user-images.githubusercontent.com/12615975/48315951-d8ec6a80-e5d4-11e8-92fa-bc9a6039b41f.png)
